server:
  port: 8081
  shutdown: graceful
  tomcat:
    threads:
      max: 150
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
  task:
    scheduling:
      pool:
        size: 10

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

mail:
  host: ENC(2PviuayFL6dKe91WydIBx81bpSBoI3FU)
  username: ENC(Hj0Qwzuifugz4sfvDCq9H0u7+WZC4nL+)
  password: ENC(WmCiOlJl61IIAfUIuIkWgKjXEE1GLIL5)
  sender:
    email: ENC(Pv5Gvm0N7LAl4wx51TrKXrkDENW2VIvpW4Ae3ZIod+I=)
    name: ENC(mCgRGGxEhhOBxoVnSOrbJxKMEWBjrDLd)

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: prometheus, health
