spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

schedule:
  enable: true
  resend-mail: true
  delete-mail: true

file:
  upload:
    location: ENC(sC+qXiI6EobSpCEDLmoWyCUiV+b8eJiJxOsQIyGP/9mopq8ZAlbGHg==)
